version: 0.0
os: linux
files:
  - source: CodeBuild-SampleCore/build_output
    destination: /home/ec2-user/aspnetcoreapp
  - source: scripts/virtualhost.conf
    destination: /home/ec2-user/aspnetcoreapp
hooks:
  ApplicationStop:
    - location: scripts/stop_service.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/remove_application.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/install_dotnetcore.sh
      timeout: 500
      runas: root

    - location: scripts/install_httpd.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 300
      runas: root
